const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Book Modules',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'Module1/intro',
        },
        {
          type: 'category',
          label: 'Module 1 Chapters',
          items: [{ type: 'autogenerated', dirName: 'Module1' }],
        },

        {
          type: 'doc',
          id: 'Module2/intro',
        },
        {
          type: 'category',
          label: 'Module 2 Chapters',
          items: [{ type: 'autogenerated', dirName: 'Module2' }],
        },

        {
          type: 'doc',
          id: 'Module3/module3',
        },
        {
          type: 'category',
          label: 'Module 3 Chapters',
          items: [{ type: 'autogenerated', dirName: 'Module3' }],
        },

        {
          type: 'doc',
          id: 'Module4/intro',
        },
        {
          type: 'category',
          label: 'Module 4 Chapters',
          items: [{ type: 'autogenerated', dirName: 'Module4' }],
        },
      ],
    },
  ],
};

module.exports = sidebars;
